FROM php:7.2-apache

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions gd xdebug

ADD xdebug.ini /etc/php/7.2/mods-available/xdebug.ini